#!/bin/bash
# ══════════════════════════════════════════════════════════
# WHY THIS SCRIPT?
# Deploys all 9 ShopSphere components in dependency order —
# discovery-server and the connection Secret first (everything
# else depends on them), then the 6 backend services, then
# api-gateway, then storefront last (it calls api-gateway).
#
# Each `helm install` uses the SAME chart (../helm/microservice)
# with a DIFFERENT values file — see Chart.yaml for why.
#
# USAGE:
#   1. kubectl apply -f ../namespace.yaml
#   2. kubectl apply -f ../../ansible/../kubernetes/base/secrets.generated.yaml
#      (generated by: ansible-playbook playbooks/generate-k8s-secrets.yml)
#   3. ./deploy-all.sh
# ══════════════════════════════════════════════════════════
set -e

CHART=../helm/microservice
NAMESPACE=shopsphere

echo "── 1. discovery-server (everything registers with this) ──"
helm install discovery-server $CHART -f discovery-server.yaml -n $NAMESPACE

echo "── waiting for discovery-server to be ready ──"
kubectl rollout status deployment/discovery-server -n $NAMESPACE --timeout=120s

echo "── 2. backend services ──"
helm install auth-service         $CHART -f auth-service.yaml         -n $NAMESPACE
helm install product-service      $CHART -f product-service.yaml      -n $NAMESPACE
helm install order-service         $CHART -f order-service.yaml        -n $NAMESPACE
helm install payment-service       $CHART -f payment-service.yaml      -n $NAMESPACE
helm install inventory-service     $CHART -f inventory-service.yaml    -n $NAMESPACE
helm install notification-service  $CHART -f notification-service.yaml -n $NAMESPACE

echo "── 3. api-gateway (routes to all of the above) ──"
helm install api-gateway $CHART -f api-gateway.yaml -n $NAMESPACE
kubectl rollout status deployment/api-gateway -n $NAMESPACE --timeout=120s

echo "── 4. storefront (calls api-gateway) ──"
helm install storefront $CHART -f storefront.yaml -n $NAMESPACE

echo ""
echo "Done. Get external URLs with:"
echo "  kubectl get svc -n $NAMESPACE api-gateway storefront"
